spring:
  profiles:
    active: dev
  application:
    name: "Order Flow MS"

server:
  servlet:
    context-path: "/orderflow/v1"

logging:
  level:
    root: INFO
    org:
      springdoc: DEBUG
      mongodb:
        driver: WARN
      apache: ERROR
      springframework:
        web: DEBUG
        boot: INFO